/*
 * 
 * 
 * 
 */
package Jeu;

import javax.swing.JButton;

/**
 *
 * @author Aymene
 */
public class AchatCarteDlg extends javax.swing.JDialog {
    
    public LesJoueurs listJ; //permet de restituer les joueurs qui vont jouer au cours du jeu
    private int nbCol; //attribut permettant de realiser la carte avec les dimensions voulues, un nombre de colonnes prédéfini
    private int nbLig; //attribut permettant de realiser la carte avec les dimensions voulues, un nombre de lignes prédéfini
    private int nbNum; //nombre de numéro comporté dans la carte loto
    private Joueur jc; //attribut permettant de manipuler chaque joueur 
    private CarteLoto cc; //attribut de la carte loto
    private boolean achat; //attribut qui va permettre de voir si l'achat est accompli dans l'application principale
    
    public int getNbCol() {
        return this.nbCol;
    }
    
    public boolean getAchat() {
        return this.achat;
    }

    /**
     * Creates new form AchatCarteDlg
     */
    public AchatCarteDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj, int nl, int nc, int nn) {
        super(parent, modal);
        //initialisation des attributs evec les valeurs en parametres
        this.listJ = lj; 
        this.nbLig = nl;
        this.nbCol = nc;
        this.nbNum = nn;
        this.achat = false;
        this.jc = this.listJ.getJoueur(0);
        this.cc = new CarteLoto(nbCol, nbNum); //instanciation de la classe CarteLoto avec deux parametres
        initComponents();
        this.remplirListeJoueurs(); //appel a la methode d'initialisation des joueurs al jcombobox
        this.initCarte(); //appel a la methode d'initialisation de la carte
        this.afficheCartes(); //appel a la methode d'affichage de la carte
    }
    
    public void remplirListeJoueurs() { //remplissage de la jComboBox par les joueurs presents
        for(int i = 0; i < this.listJ.getNbJoueur(); i++) {
            String pseudo = this.listJ.getJoueur(i).getPseudo();
            this.jComboBox1.addItem(pseudo);
        }
    }
    
    public void initCarte() { //initialisation de la carte
        for(int i = 0; i < this.getNbCol() * this.nbLig; i++) {
            JButton button = new JButton();
            jPanel2.add(button);
        }
    }
    
    public void afficheCartes() { //methode permettant l'affichage des cartes dans la jpanel centrale
        cc.initValeursCarte();
        int n = 0;
        for(int i = 0; i < cc.getNbLig(); i++) {
            for(int j = 0; j < cc.getNbCol(); j++) {
                JButton jb = (JButton)jPanel2.getComponent(n);
                if(cc.getValCase(i, j) == 0) {
                    jb.setText(" ");
                }
                else {
                    String str = "" + cc.getValCase(i, j);
                    jb.setText(str);
                }
                n++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Acheter une ou plusieurs cartes");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(3, getNbCol()));
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("'Joueur' dispose de 20.0€");
        jPanel4.add(jLabel2);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1);

        jButton1.setText("Autre choix");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setText("Acheter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.jc.getSolde() >= 5) {
            CarteLoto cl = new CarteLoto(nbCol, nbNum);
            cl.initValeursCarte();
            this.jc.acheterCarte(cl); //appel a la methode d'achat de carte qui ajoute la carte au cartes du joueur
            //affichage du solde de chaque joueur apres achat de chaque carte
            jLabel2.setText(this.jc.getPseudo() + " dispose de " + this.jc.getSolde() + "€");
            this.afficheCartes();
            this.achat = true;
        }
        else {
            jLabel2.setText(this.jc.getPseudo() + " dispose de " + this.jc.getSolde() + "€, vous ne pouvez pas acheter de cartes"); //impossible d'acheter plus de cartes
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //fermeture de la jDialog
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //affichage du solde de chaque joueur
        int index = jComboBox1.getSelectedIndex();
        if(index != -1) {
            this.jc = this.listJ.getJoueur(index);
            jLabel2.setText(this.listJ.getJoueur(index).getPseudo() + " dispose de " + this.listJ.getJoueur(index).getSolde() + "€");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //changement de carte en initialisant une nouvelle
        CarteLoto cl = new CarteLoto(nbCol, nbNum);
        this.cc = cl;
        this.afficheCartes();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AchatCarteDlg dialog = new AchatCarteDlg(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
