package Jeu;

import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Aymene
 */
public class OptionDlg extends javax.swing.JDialog {
    
    private int choixOpt; //permet de stocker l'indice du choix de l'option du jeu
    private String choixOptNom; //nom de l'option
    private int nbCol; //permet de stocker le nombre de colonnes de la carte loto
    private int nbNum; //permet de stocker le nombre a figurer sur une carte loto
    private Lot l; //pour savoir quel lot
    private Lots lots; //permet de stocker les lots de la partie
    private int[] col = {5, 6, 7, 8, 9}; //valeur de colonnes stockée dans un tableau
    private boolean ok;
    
    //accesseurs
    public int getChoix() {
        return this.choixOpt;
    }
    
    public int getNbCol() {
        return this.nbCol;
    }
            
    public int getNbNum() {
        return this.nbNum;
    }
    
    public boolean getOk() {
        return this.ok;
    }
    
    public String getchoixOptNom() {
        return this.choixOptNom;
    }
    
    public Lot getLot() {
        return this.l;
    }

    /**
     * Creates new form OptionDlg
     */
    public OptionDlg(java.awt.Frame parent, boolean modal, boolean ca, int nc, int nn) {
        super(parent, modal);
        initComponents();
        this.remplirComboCol(); //appel a la methode de remplissage
        ButtonGroup bg = new ButtonGroup(); //regroupement des boutons radio dans un ButtonGroup
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(jRadioButton3);
        jRadioButton1.setSelected(true); //initialisation de la selection sur le premier choix
        this.choixOpt = 1;
        if(!ca) {
            this.nbCol = 5;
            this.nbNum = 5;
        }
        else {
            this.nbCol = nc;
            jComboBox1.setSelectedIndex(nc);
            jComboBox1.setEnabled(false);
            this.nbNum = nn;
            jTextField1.setText("" + nn);
            jTextField1.setEnabled(false);
            jLabel6.setText("Nombre de colonnes et de numéros non modifiables");
        }
        this.lots = new Lots(); //instanciation de la classe Lots
    }
    
    public void remplirComboCol() { //remplissage de la jComboBox par les nombres possibles
        for(int i : col) {
            jComboBox1.addItem("" + i);
        }
    }
    
    public void initLots() { //methode qui permet d'initialiser les lots a partie de l'option choisie à l'aide d'un switch-case
        int opt = this.choixOpt;
        int n;
        Image img;
        Image newImg;
        switch(opt) {
            case 1 : 
                Lot l1_1 = new Lot("Bon d'achat Carrefour 10€");
                l1_1.setNiv(1);
                l1_1.setPhoto(new ImageIcon(getClass().getResource("../img/10euro.jpg")));
                this.lots.ajouteLot(l1_1);
                Lot l1_2 = new Lot("Souris Gamer RGB");
                l1_2.setNiv(1);
                l1_2.setPhoto(new ImageIcon(getClass().getResource("../img/mouse.jpg")));
                this.lots.ajouteLot(l1_2);
                break;
            case 2 : 
                Lot l2_1 = new Lot("Bon d'achat Carrefour 20€");
                l2_1.setNiv(2);
                l2_1.setPhoto(new ImageIcon(getClass().getResource("../img/20euro.png")));
                this.lots.ajouteLot(l2_1);
                Lot l2_2 = new Lot("Clavier Gamer RGB");
                l2_2.setNiv(2);
                l2_2.setPhoto(new ImageIcon(getClass().getResource("../img/keyboard.jpg")));
                this.lots.ajouteLot(l2_2);
                break;
            case 3 : 
                Lot l3_1 = new Lot("Bon d'achat Carrefour 30€");
                l3_1.setNiv(3);
                l3_1.setPhoto(new ImageIcon(getClass().getResource("../img/30euro.jpg")));
                this.lots.ajouteLot(l3_1);
                Lot l3_2 = new Lot("Chaise Gamer DXRacer");
                l3_2.setNiv(3);
                l3_2.setPhoto(new ImageIcon(getClass().getResource("../img/dxracer.jpg")));
                this.lots.ajouteLot(l3_2);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Option du jeu");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Option du jeu");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Comment voulez vous jouer?");
        jPanel4.add(jLabel2);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Quine - Une ligne complète");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Double Quine - Deux lignes complètes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("Carton Plein - Trois lignes complètes");
        jPanel4.add(jRadioButton3);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(4, 0));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Configuration des cartons");
        jPanel6.add(jLabel3);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Combien de colonnes?");
        jPanel7.add(jLabel4);

        jPanel7.add(jComboBox1);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Combien de numéro?");
        jPanel8.add(jLabel5);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField1);

        jPanel5.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel9.add(jLabel6);

        jPanel5.add(jPanel9);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //fermeture de la jdialog
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //le clique sur valider fait un tirage aleatoire qui choisira un lot aleatoirement
        int n;
        if(jRadioButton1.isSelected()) {
            this.choixOpt = 1;
            this.choixOptNom = "Quine";
            this.initLots();
            n = Integer.parseInt(Math.round(Math.random()) + "");
            this.l = this.lots.getLot(n);
        } else if(jRadioButton2.isSelected()) {
            this.choixOpt = 2;
            this.choixOptNom = "Double Quine";
            this.initLots();
            n = Integer.parseInt(Math.round(Math.random()) + "");
            //n = (int)(1 + Math.random());
            this.l = this.lots.getLot(n);
        } else if(jRadioButton3.isSelected()) {
            this.choixOpt = 3;
            this.choixOptNom = "Carton Plein";
            this.initLots();
            n = Integer.parseInt(Math.round(Math.random()) + "");
            //n = (int)(1 + Math.random());
            this.l = this.lots.getLot(n);
        }
        //fixation des valeurs choisies dans la jcombobox et la jtextfield
        int index = jComboBox1.getSelectedIndex();
        this.nbCol = this.col[index];
        int i;
        if(jTextField1.getText().equals("") || jTextField1.getText().equals(null)) {
            jLabel6.setText("Entrez un nombre de numéros");
        }
        else {
            String s = jTextField1.getText();
            try {
                i = Integer.parseInt(s);
                if(i < 5 || i > this.getNbCol() * 3) {
                    jLabel6.setText("Entrez un nombre de numéros valide");
                }
                else {
                    this.nbNum = i;
                    this.setVisible(false);
                    this.dispose();
                }
            } catch(NumberFormatException e) {
                jLabel6.setText("Entrez un nombre de numéros valide");
            }
        }
        this.ok = true; //fixation du ok de fermeture sur true
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                OptionDlg dialog = new OptionDlg(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
